### ISSUE TITLE
Not able to run on iPhone 12 max pro iOS version 14.4

### ISSUE THREAD

**Issue by mohd14shoeb** [rizwanch173/Flutter-Social-App-UI-Kit#1]

**Comment by rizwanch173** [comment]
hi there, the code is updated Flutter 2.2.0 now you can run on any iOS device 14.4 as well.
Please Check the ScreenShot.

### Please update your flutter to the latest version Flutter 2.2.0

![Screen Shot 2021-05-24 at 1 45 20 AM](https://user-images.githubusercontent.com/57150383/119276000-b752ac00-bc31-11eb-944f-d48ad1f0177f.png)

**Comment by mohd14shoeb** [comment]
Still having same issue
                                                              ^^^^^^
    ../../../../flutter/packages/flutter/lib/src/widgets/localizations.dart:413:17: Context: Found this candidate, but the arguments don't match.
      static Locale localeOf(BuildContext context) {
                    ^^^^^^^^
    Command PhaseScriptExecution failed with a nonzero exit code
    note: Using new build system
    note: Building targets in parallel
    note: Planning build
    note: Constructing build description
Could not build the application for the simulator.
Error launching application on iPhone 12 Pro Max.

**Comment by rizwanch173** [comment]
localizations.dart
there is an issue with your flutter SDK, this project didn't use any third-party plugin that makes trouble.
